DATASET_NUM_STEPS = 5
DATASET_BIN_WIDTH = 20 * 4e-3
DATASET_LABEL_SERIES = True

DATALOADER_SHUFFLE = [True, True]
DATALOADER_BATCH_SIZE = [256, 256]

MODEL_GRU_LAYER_DIMS = [32]
MODEL_OUTPUT_SERIES = DATASET_LABEL_SERIES
MODEL_OUTPUT_DIM = 2
# MODEL_LOG_FOCUS_FACTOR = 10.0
MODEL_HIDDEN_DIM = 128
MODEL_LATENT_DIM = 32
MODEL_LOSS_RATIO = [1.0, 0.0, 10.0]

PREPROCESSORS = []
AUGMENTATORS = ["Jittering"]

TRAIN_NUM_EPOCHS = 50
FINETUNE_NUM_EPOCHS = 10

TEST_DATALOADER_BATCH_SIZE = 256

OTHER_INFO = "softplus and log for input data, bn for mu. prune 0.5 of weights, ft with valset, seed 109"