DATASET_NUM_STEPS = 7
DATASET_BIN_WIDTH = 7 * 4e-3
DATASET_LABEL_SERIES = False

DATALOADER_SHUFFLE = [True, False]
DATALOADER_BATCH_SIZE = [256, 256]

MODEL_NUM_STEPS = DATASET_NUM_STEPS
MODEL_LAYER1 = 32
MODEL_LAYER2 = 48
MODEL_OUTPUT_DIM = 2

TRAIN_NUM_EPOCHS = 20

TEST_DATALOADER_BATCH_SIZE = -1

TESTMODELADD_BIN_WIDTH = DATASET_BIN_WIDTH