DATASET_NUM_STEPS = 1
DATASET_BIN_WIDTH = 50 * 4e-3
DATASET_LABEL_SERIES = False

DATALOADER_SHUFFLE = [True, False]
DATALOADER_BATCH_SIZE = [256, 256]

MODEL_LAYER1 = 32
MODEL_LAYER2 = 48
MODEL_OUTPUT_DIM = 2

TRAIN_NUM_EPOCHS = 20

TEST_DATASET_NUM_STEPS = 1
TEST_DATALOADER_BATCH_SIZE = 1
TEST_DATALOADER_SHUFFLE = False