DATASET_NUM_STEPS = 7
DATASET_BIN_WIDTH = 50 * 4e-3
DATASET_LABEL_SERIES = False

DATALOADER_SHUFFLE = [True, False]
DATALOADER_BATCH_SIZE = [256, 256]

MODEL_GRU_LAYER_DIMS = [32]
MODEL_OUTPUT_SERIES = DATASET_LABEL_SERIES
MODEL_OUTPUT_DIM = 2

TRAIN_NUM_EPOCHS = 20

TEST_DATALOADER_BATCH_SIZE = -1
TEST_NETWORK = "v1"

TESTMODELADD_BIN_WIDTH = DATASET_BIN_WIDTH
TESTMODELADD_NUM_STEPS = DATASET_NUM_STEPS

OTHER_INFO = "always zero initial hidden state, original reverse order"